<a href="https://colab.research.google.com/github/vipin0761/Data_Science/blob/main/numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

	• numpy is a numerical computing library for python
	• numpy support multi domensional arrays and matrices
	• it has a lot of in-built mathematical functions
    
    why Numpy
	• perform fast operations ( because of vectorization )
	• numpy arrays can be treated as vectors and matrices from linear algebra

In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
%timeit arr**2

470 ns ± 3.19 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


array: Fundamental element in numpy is homogenous array. Numpy arrays can be 1D, 2D, 3D ..... nD

different ways to create np arrays
    1. np.array()
    2. np.arange()

Special arrays in Numpy

    Zeros()
    ones()
    diag()
    identity()


###### declaring numpy array

In [ ]:
np_arr = np.array([1,2,3,4,5])
np_arr

array([1, 2, 3, 4, 5])

In [ ]:
new_arr = np.arange(1,13,2)
new_arr

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np_zeros = np.zeros((3,3,))
np_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np_ones = np.ones((3,3))
np_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np_diag = np.diag([1,2,3])
np_diag

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
np_identity = np.identity(3)
np_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
type(np_arr)

numpy.ndarray

In [ ]:
np_arr.ndim # no. of dimensions of the array

1

In [ ]:
np_arr.shape # (no. of rows, no. of columns)

(5,)

###### Indexing in Array

In [ ]:
new_arr = np.random.randint(10, 100, (5,4))
new_arr

array([[21, 21, 54, 88],
       [21, 43, 98, 37],
       [10, 15, 36, 64],
       [76, 75, 53, 29],
       [12, 29, 78, 15]])

In [ ]:
new_arr.shape

(5, 4)

In [ ]:
new_arr[1]
new_arr[-1] # access row

array([12, 29, 78, 15])

In [ ]:
new_arr[1,1] # access element

43

###### Array Slicing

In [ ]:
# arr [ start row index: end row index + 1, start column index : end column index + 1 ]

In [ ]:
new_arr [0:,1:2]

array([[21],
       [43],
       [15],
       [75],
       [29]])

###### masking

In [ ]:
mask = new_arr > 25
mask

array([[False, False,  True,  True],
       [False,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [False,  True,  True, False]])

In [ ]:
new_arr[mask] # get all emenets greater than 25

array([54, 88, 43, 98, 37, 36, 64, 76, 75, 53, 29, 29, 78])

In [ ]:
np.sum(mask) = no of elements greater than 25

SyntaxError: cannot assign to function call (1781982963.py, line 1)

Basic operations on arrays
+,-,*,/,%,** are elementary operators and can be performed on any 2 matrix of same shape

In [ ]:
a = np.array([10,20,30,40])
b = np.arange(1,5)
print(a,b)
print(a+b)
print(a-b)
print(np.log(a))
print(np.sin(a))
print(np.sqrt(a))
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))

In [ ]:
# matrix product
A = np.random.randint(0,5,(3,4))
B = np.random.randint(0,5,(4,2))
print(np.dot(A,B))

In [ ]:
# reshape array
n = np.arange(0,24)
b = n.reshape(6,4)
print(b)
print(np.sum(b, axis=0)) # sum column wise
print(np.sum(b, axis=1)) # sum row wise

In [ ]:
# Shape manipulation
print(b.flatten()) # convert the array to 1D
print(b.reshape(8,3)) # reshape the array (new size should have same no of elements)
print(b.T) # transpose the array
print(np.transpose(b)) # transpose the array

In [ ]:
# stacking of arrays
a = np.random.randint(0,5,(2,2))
b = np.random.randint(0,5,(2,2))

print(np.hstack((a,b))) # horizontal stacking
print(np.vstack((a,b))) # vertical stacking

###### Broadcasting
    2 arrays can perform operations in numpy only when they have the same shapes
    broadcasting let two arrays of different shapes to do some operations
        a small array will repeat itself, and convert to the same shape as of another array


In [ ]:
A = np.random.randint(0,5,(3,3))
a = np.array([1,2,3])
print(A+a)
print(A+a.T)

###### vectorization -- refers to performing operations directly on arrays