<a href="https://colab.research.google.com/github/vipin0761/Data_Science/blob/main/3.%20basics%20of%20data%20science/5.%20numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
ar = np.array([1,2,3,4]) # convert a list into a array
np.asarray([1,2,3,4])
p.asanyarray([1,2,3,4])

In [ ]:
b = np.matrix([1,2,3]) # converts it into a 2-D array

In [ ]:
d = np.copy(a) # copy array by value rather than by reference

In [ ]:
np.fromfunction(lambda i, j : i==j , (3,3)) # generating arrays from functions

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i, j : i*j , (3,3))

In [ ]:
iterable = (i*i for i in range(5)) # generating array from iterable
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('234 234' , sep= ' ') # generating array from string

array([234., 234.])

### Numpy - Data Types.

In [ ]:
ar = np.array([[1,2,3,4] , [2,3,4,5]])

In [ ]:
ar.ndim # tells you the no. of dimensions of the matrix
ar.size # tells you the no of elements in the matrix
ar.dtype # data type of elements of matrix
ar.shape # tells you the (rows, columns)

(2, 4)

In [ ]:
np.arange(2.3,3.4, 0.1) # arange can take float values while range cannot

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3])

In [ ]:
np.linspace(1,5,10) # produces n elements in between a particular interval -- linspace(start, end, n)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(2,5 , 10, base = 2) # generates the logs of n elements in between a particular interval  --- linspace(start, end, n, base=b)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(4) # similar method to create array of one's
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
on = np.ones(4)
on + 5


array([6., 6., 6., 6.])

In [ ]:
np.empty((3,4)) # creates an empty array
np.eye(2) # identity matrix

array([[1., 0.],
       [0., 1.]])

In [ ]:
arr = np.random.randn(3,4) # generates random numbers based on standard normal distribution
np.random.rand(3,4) # generates random numbers
np.random.randint(1,110 , (3,4)) # generat random intergers within a range

In [ ]:
arr = np.random.rand(3,4)
arr.reshape(6,-1) # reshape array

array([[0.25227869, 0.17260962],
       [0.75186594, 0.14098546],
       [0.78671403, 0.30848691],
       [0.1883532 , 0.6161819 ],
       [0.01503523, 0.52411934],
       [0.78788764, 0.60524717]])

In [ ]:
arr = np.random.randint(1,100 , (5,5))

In [ ]:
arr[arr>50] # filter all elements  > 50

array([83, 56, 55, 78, 72, 68, 86, 75, 89, 91, 52, 51])

In [ ]:
arr[2:4 , [1,2]] # row and column slicing

array([[49, 86],
       [52, 13]])

### NumPy Array Indexing

In [ ]:
# Slicing array
temp = arr[:2, ::2]

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]

### NumPy – Unary Operators

In [ ]:
arr.max()
arr.max(axis = 1)
arr.min(axis = 0)
arr.sum()
arr.cumsum(axis = 1)

### NumPy – Binary Operators

In [ ]:
# add arrays
print ("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

### NymPy’s ufuncs

In [ ]:
np.sin(a)
np.exp(a)
np.sqrt(a)

### operations on array

In [ ]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))
arr1+arr2
arr1-arr2
arr1/arr2
arr1 * arr2
arr1@arr2 # matrix multiplication
arr1/0
arr1 +100
arr1**2

### Numpy – Broadcasting.

In [ ]:
arr =np.zeros((4,4))  # perform broadcasting row wise
row = np.array([1,2,3,4])
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
col = np.array([[1,2,3,4]]) # perform broadcasting column wise
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

### Mathematical functions on array

In [ ]:
 arr1 = np.random.randint(1,4 , (3,4))

In [ ]:
np.sin(arr1)
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.41421356, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.41421356],
       [1.        , 1.41421356, 1.41421356, 1.        ]])

In [ ]:
np.exp(arr1)
np.log10(arr1)
# Transpose of Array
Trans_arr = arr1.T