<a href="https://colab.research.google.com/github/vipin0761/Data_Science/blob/main/numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Numpy - Array Manipulation.

In [1]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10 , (3,4))
arr.T # transpose an array
arr.reshape(2,6) # reshape an array
arr.flatten() # convert the data into 1 dimension

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
np.expand_dims(arr1 ,axis=1)  # expand the array to 2-d  axis = 1 expand across column || axis = 0 expand across row

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
data = np.array([[1] , [2] , [3]]) # squeeze and combine data to single row
np.squeeze(data)

array([1, 2, 3])

In [5]:
np.repeat(arr1, 3) # repeat array n times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [ ]:
np.roll(arr1 , 3) # rotate array by n places

array([3, 3, 4, 1, 2])

In [ ]:
np.diag(arr1) # create a diagonal array of a row

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

###Numpy - Binary Operators.

In [6]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [ ]:
arr1 & arr2
~arr1
arr1|arr2

###Numpy - String Functions.

In [ ]:
arr = np.array(['sudh' , "Kumar"])

In [ ]:
np.char.upper(arr)
np.char.title(arr)
np.char.capitalize(arr)

###Numpy - Mathematical Functions.

In [ ]:
np.sin(arr1)
np.cos(arr1)
np.tan(arr1)
np.tanh(arr1)
np.log10(arr1)
np.exp(arr1)
np.sqrt(arr1)
np.power(arr1,2)
np.mean(arr1)
np.median(arr1)
np.std(arr1)
np.var(arr1)
np.min(arr1)
np.max(arr1)