<a href="https://colab.research.google.com/github/vipin0761/Data_Science/blob/main/3.%20basics%20of%20data%20science/7.%20numpy_part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Sort, Search & Counting Functions.

In [ ]:
import numpy as np

In [ ]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [ ]:
np.sort(arr)
np.searchsorted(arr ,34)
np.count_nonzero(arr)
np.where(arr > 6)
np.extract(arr>3 , arr)

(array([5, 8]),)

###Numpy - Byte Swapping.

In [ ]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [ ]:
arr.byteswap()

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

###Numpy - Copies &Views.

In [ ]:
a = np.copy(arr) # deep copy
b = arr.view() # shalllow copy

###Numpy - Matrix Library.

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

###Numpy - Linear Algebra

In [ ]:
arr1 = np.random.randint([[2,3] , [4,5]])
arr2 = np.random.randint([[5,3] , [2,5]])

In [ ]:
np.dot(arr1,arr2) # dot product of matrix
arr1@arr1

array([[ 7,  8],
       [12, 15]])